In [ ]:
import tensorflow as tf
matrix1 = tf.Variable([[11,12,13,14], [15,16,17,18]])

In [ ]:
matrix1.shape.as_list()


[2, 4]

In [ ]:

reshape1 = tf.reshape(matrix1, shape=[4, 2])
reshape1


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]], dtype=int32)>

In [ ]:
reshape1.shape.as_list()


[4, 2]

In [ ]:
reshape2 = tf.reshape(matrix1, shape=[1, 8])
reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[11, 12, 13, 14, 15, 16, 17, 18]], dtype=int32)>

In [ ]:
reshape2.shape.as_list()

[1, 8]

In [ ]:
reshape3 = tf.reshape(matrix1, shape=[8, 1])
reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18]], dtype=int32)>

In [ ]:
reshape3.shape.as_list()

[8, 1]

In [ ]:
reshape4 = tf.reshape(matrix1, shape=[2, 2, 2])
reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 12],
        [13, 14]],

       [[15, 16],
        [17, 18]]], dtype=int32)>

In [ ]:
reshape4.shape.as_list()

[2, 2, 2]

In [ ]:
tf.rank(reshape4).numpy()


3

In [ ]:

transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]], dtype=int32)>

In [ ]:
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

In [ ]:
transpose2 = tf.transpose(reshape4)
transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 15],
        [13, 17]],

       [[12, 16],
        [14, 18]]], dtype=int32)>