In [ ]:
import tensorflow as tf

In [ ]:
df = tf.data.experimental.make_csv_dataset(r'/content/sample_data/dataset/drugLibTrain_raw.tsv',
                                           batch_size=1, field_delim='\t')

In [ ]:
def prep_ds(ds, shuffle_buffer_size=1024, \
                batch_size=32):
        # Shuffle the dataset
        ds = ds.shuffle(buffer_size=shuffle_buffer_size)
        # Repeat the dataset
        ds = ds.repeat()
        # Batch the dataset
        ds = ds.batch(batch_size)
        return ds


In [ ]:
ds = prep_ds(df, batch_size=5)


In [ ]:

for x in ds.take(1):\
        print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[3134],
       [2034],
       [  58],
       [1585],
       [ 736]], dtype=int32)>), ('urlDrugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'geodon'],
       [b'protonix'],
       [b'flexeril'],
       [b'xanax'],
       [b'flonase']], dtype=object)>), ('rating', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[10],
       [ 9],
       [ 7],
       [ 9],
       [ 8]], dtype=int32)>), ('effectiveness', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Highly Effective'],
       [b'Considerably Effective'],
       [b'Moderately Effective'],
       [b'Highly Effective'],
       [b'Considerably Effective']], dtype=object)>), ('sideEffects', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Mild Side Effects'],
       [b'No Side Effects'],
       [b'Mild Side Effects'],
       [b'Mild Side Effects'],
       [b'No Side Effects']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1),

In [ ]:
import tensorflow_hub as hub
embedding = "https://tfhub.dev/google/tf2-preview"\
                "/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], \
                               dtype=tf.string, \
                               trainable=True)

In [ ]:
hub_layer

In [ ]:
for x in ds.take(1):\
        print(hub_layer(tf.reshape(x['commentsReview'],[-1])))

tf.Tensor(
[[ 0.99992615 -1.4787403   0.9104399   0.86711144 -0.7115203  -1.9166865
   0.06280978  1.5441661   0.25094643  0.9323304  -0.8906736   0.7697992
  -0.3026149   0.38812333 -2.2003405   0.24054079  2.4877768  -0.21091937
   0.08629305 -0.6759773 ]
 [-0.23041575 -1.5811146   0.36104193  1.5134839  -3.848278   -4.6437488
  -3.937187    0.58357525  0.6790218   1.9861951  -3.3569562   2.1706052
   2.0913982   0.5812193  -4.5686526   1.3868291   3.1421504  -1.1857198
  -1.2496771  -1.0205247 ]
 [-0.36539942 -0.8013048   0.35457462  0.08301509 -0.45976642 -1.7258607
  -0.5027563  -0.05774986  0.33898318 -0.3666331  -0.17903027  1.2632741
  -0.08526731  0.32043096 -1.7655134   1.2066952   0.59091246 -1.2970936
  -0.95476353 -0.25929165]
 [ 0.0220382  -1.0279671   0.48598352  0.94237864 -0.8682695  -2.3244507
  -1.9349945   0.29138783  0.4787122  -0.39143276 -0.9478254   1.5726681
   0.23979051  0.03509539 -2.07867     1.7662379   2.5890708  -1.5879182
  -0.48062128 -0.4635673 ]
 [-0